<script setup lang="ts">
// Global imports and props
import { vIntersectionObserver } from '@vueuse/components';

const {
  selections,
  hasAutoGenerated,
  industryOptions,
  toneOfVoiceOptions,
  errorMessageIndustry,
  errorMessageToneOfVoice,
  postData,
  getIndustryOptions,
  getToneOfVoiceOptions,
  pickRandomOptions,
} = useShowcase();
const { generatePost, generateRecommendation } = showcaseApi();

defineProps({
  showcaseTitle: {
    type: String,
    required: true,
  },
});

// States
const isLoading = ref(false);
const errorMessage = ref('');
const isResetDisabled = ref(true);
const animatingArrows = ref({
  first: false,
  second: false,
  third: false,
});
const limitError = ref(false);
const visibleContent = ref({
  post: postData.value.post_image !== '',
  impressions: postData.value.chartData.length > 0,
  tip: postData.value.tip !== '',
});

// Functions
const handleGenerateTip = async () => {
  try {
    const response = await generateRecommendation();
    postData.value.tip = response.recommendation;
    postData.value.total = response.impressions;
    postData.value.percentage = `${response.percentage_impression}%`;
  } catch (error: any) {
    if (error.response.status === 429) {
      limitError.value = true;
      setTimeout(() => {
        limitError.value = false;
      }, 6000);
      isLoading.value = false;
      return;
    }
    errorMessage.value
      = 'Something went wrong, we couldn\'t generate a tip for you. Please contact us';
    isLoading.value = false;
  } finally {
    isLoading.value = false;
  }
};

const handleGeneratePost = async () => {
  try {
    const response = await generatePost(selections.value);
    postData.value.post_image = response.post_image;
    postData.value.post_text = response.post_text;
  } catch (error: any) {
    if (error.response.status === 429) {
      limitError.value = true;
      setTimeout(() => {
        limitError.value = false;
      }, 6000);
      isLoading.value = false;
      return;
    }
    errorMessage.value
      = 'Something went wrong, we couldn\'t generate a post for you. Please contact us';
    isLoading.value = false;
  }
};
const timeoutIds = ref<Record<string, NodeJS.Timeout>>({
  first: setTimeout(() => {}, 0),
  second: setTimeout(() => {}, 0),
  third: setTimeout(() => {}, 0),
});

const clearTimeouts = () => {
  clearTimeout(timeoutIds.value.first);
  clearTimeout(timeoutIds.value.second);
  clearTimeout(timeoutIds.value.third);
};

const startAnimation = () => {
  visibleContent.value.post = true;
  timeoutIds.value.first = setTimeout(() => {
    animatingArrows.value.second = true;
    animatingArrows.value.first = false;
    visibleContent.value.impressions = true;
  }, 3500);
  timeoutIds.value.second = setTimeout(() => {
    animatingArrows.value.third = true;
    animatingArrows.value.second = false;
    visibleContent.value.tip = true;
  }, 5000);
  timeoutIds.value.third = setTimeout(() => {
    animatingArrows.value.third = false;
  }, 12000);
};
const stopPostGeneration = () => {
  visibleContent.value = {
    post: false,
    impressions: false,
    tip: false,
  };
  animatingArrows.value = {
    first: false,
    second: false,
    third: false,
  };
  postData.value = {
    post_image: '',
    post_text: '',
    tip: '',
    total: null,
    percentage: '',
    chartData: [],
  };
  isLoading.value = false;
  clearTimeouts();
};

const handleGenerate = async () => {
  isResetDisabled.value = true;
  if (
    selections.value.industry === ''
    && selections.value.tone_of_voice === ''
  ) {
    errorMessage.value = 'Please select an industry and a tone of voice!';
    isLoading.value = false;
    return;
  }
  if (selections.value.industry === '') {
    errorMessage.value = 'Please select an industry!';
    isLoading.value = false;
    return;
  }
  if (selections.value.tone_of_voice === '') {
    isLoading.value = false;
    errorMessage.value = 'Please select a tone of voice!';
    return;
  }
  clearTimeouts();
  visibleContent.value = {
    post: false,
    impressions: false,
    tip: false,
  };
  animatingArrows.value = {
    first: false,
    second: false,
    third: false,
  };
  isLoading.value = true;
  animatingArrows.value.first = true;

  await handleGeneratePost();
  if (limitError.value) {
    stopPostGeneration();
    return;
  }

  postData.value.chartData = Array.from({ length: 7 }, () =>
    Math.floor(Math.random() * 41 + 40),
  );
  await handleGenerateTip();
  if (limitError.value) {
    stopPostGeneration();
    return;
  }
  isLoading.value = false;
  hasAutoGenerated.value = true;
  startAnimation();
  isResetDisabled.value = false;
};

const handleReset = () => {
  selections.value = {
    industry: '',
    tone_of_voice: '',
  };
  limitError.value = false;
  errorMessage.value = '';
  stopPostGeneration();
};

// Watchers
watch(
  () => errorMessage.value,
  () => {
    if (errorMessage.value !== '') {
      setTimeout(() => {
        errorMessage.value = '';
      }, 4000);
    }
  },
);

watch(
  [() => selections.value.industry, () => selections.value.tone_of_voice],
  () => {
    errorMessage.value = '';
  },
);

// Lifecycle hooks
const onIntersectionObserver = async (entries: IntersectionObserverEntry[]) => {
  const { isIntersecting } = entries[0];
  if (isIntersecting && !hasAutoGenerated.value) {
    await getIndustryOptions();
    await getToneOfVoiceOptions();
    pickRandomOptions();
    await handleGenerate();
  }
};

onMounted(() => {
  if (hasAutoGenerated.value) {
    visibleContent.value = {
      post: true,
      impressions: true,
      tip: true,
    };
  }
});
</script>

<template>
  <div v-intersection-observer="onIntersectionObserver" class="showcase">
    <div class="showcase-background" />
    <div class="showcase-content">
      <div class="showcase-title">
        <LandingShowcaseTitle :title="showcaseTitle" />
      </div>
      <div class="showcase-info">
        <LandingShowcaseInfo />
      </div>
      <div class="showcase-choose">
        <LandingShowcaseChoose
          :error-message="errorMessage"
          :is-loading="isLoading"
          :industry-options="industryOptions"
          :tone-of-voice-options="toneOfVoiceOptions"
          :error-message-industry="errorMessageIndustry"
          :error-message-tone-of-voice="errorMessageToneOfVoice"
          :limit-error="limitError"
          @on-click="handleGenerate"
        />
      </div>
      <div class="showcase-post">
        <LandingShowcasePost
          :is-content-visible="visibleContent.post"
          :loading="isLoading"
        />
      </div>
      <div class="showcase-impressions">
        <LandingShowcaseImpressions
          :is-content-visible="visibleContent.impressions"
          :loading="isLoading"
        />
      </div>
      <div class="showcase-tip">
        <LandingShowcaseTip
          :is-content-visible="visibleContent.tip"
          :loading="isLoading"
          :is-reset-disabled="isResetDisabled"
          @on-reset="handleReset"
        />
      </div>
      <div
        :class="{ 'desktop-arrow-1-animating': animatingArrows.first }"
        class="desktop-arrow-1"
      >
        <IconsShowcaseDesktop1 />
      </div>
      <div
        :class="{ 'desktop-arrow-2-animating': animatingArrows.second }"
        class="desktop-arrow-2"
      >
        <IconsShowcaseDesktop2 />
      </div>
      <div
        :class="{ 'desktop-arrow-3-animating': animatingArrows.third }"
        class="desktop-arrow-3"
      >
        <IconsShowcaseDesktop3 />
      </div>
    </div>
  </div>
</template>

<style scoped>
.showcase {
  position: relative;
  padding: 24px 0 52px;
}

.showcase-content {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 0 16px;
  max-width: 420px;
  margin: 0 auto;
}

.showcase-background {
  position: absolute;
  top: 0;
  left: 0;
  right: 32px;
  background: var(--home-section-background);
  border-radius: 0px 12px 12px 0px;
  height: 95%;
  z-index: -1;
}
.showcase-title,
.showcase-info {
  max-width: 80%;
}
.showcase-choose {
  width: 100%;
  margin: 0 auto;
  z-index: 2;
}
.showcase-post {
  max-width: 224px;
  width: 100%;
  margin: -50px auto;
}
.showcase-impressions {
  max-width: 224px;
}
.showcase-tip {
  max-width: 224px;
  width: 100%;
  margin: -48px 0 0 auto;
}
.desktop-arrow-1,
.desktop-arrow-2,
.desktop-arrow-3 {
  display: none;
}
@media screen and (min-width: 700px) {
  .showcase-title,
  .showcase-info,
  .showcase-post,
  .showcase-impressions,
  .showcase-tip {
    max-width: 100%;
    margin: 0;
    z-index: initial;
  }
  .showcase-background {
    top: 64px;
  }
  .showcase-content {
    display: grid;
    grid-template-columns: repeat(12, 1fr);
    grid-template-rows: repeat(12, 44px);
    gap: 16px;
    max-width: 800px;
    padding: 0 24px;
  }
  .showcase-title {
    grid-column: 1 / 6;
    grid-row: 2 / 4;
  }
  .showcase-info {
    grid-column: 1 / 7;
    grid-row: 4 / 6;
  }

  .showcase-choose {
    grid-column: 1 / 8;
    grid-row: 6 / 10;
    align-self: flex-end;
    z-index: initial;
  }

  .showcase-post {
    grid-column: 8 / 12;
    grid-row: 1 / 10;
    align-self: flex-end;
  }

  .showcase-impressions {
    grid-column: 1 / 8;
    grid-row: 10 / 13;
  }

  .showcase-tip {
    grid-column: 8 / 12;
    grid-row: 10 / 13;
  }
}

@media screen and (min-width: 1000px) {
  .showcase-background {
    top: 0;
    height: 90%;
  }
  .showcase::before {
    content: "";
    position: absolute;
    top: -16px;
    left: 0;
    height: 1px;
    width: 100%;
    background-color: var(--blue-main);
  }

  .showcase::after {
    content: "";
    position: absolute;
    box-sizing: border-box;
    top: -32px;
    right: 16px;
    height: 216px;
    width: 1px;
    background-color: var(--blue-main);
  }

  .showcase-content {
    display: grid;
    grid-template-columns: repeat(10, 1fr);
    grid-template-rows: repeat(12, 32px);
    gap: 16px;
    max-width: 1600px;
    padding: 0 24px;
  }
  .showcase-title {
    grid-column: 1 / 9;
    grid-row: 1 / 2;
  }
  .showcase-info {
    grid-column: 1 / 4;
    grid-row: 3 / 6;
  }

  .showcase-choose {
    grid-column: 4 / 8;
    grid-row: 3 / 8;
    justify-self: center;
  }

  .showcase-post {
    grid-column: 8 / 11;
    grid-row: 1 / 13;
  }

  .showcase-impressions {
    grid-column: 4 / 8;
    grid-row: 8 / 12;
  }

  .showcase-tip {
    grid-column: 1 / 4;
    grid-row: 8 / 12;
  }

  .desktop-arrow-1,
  .desktop-arrow-2,
  .desktop-arrow-3 {
    display: none;
  }
}

@media screen and (min-width: 1400px) {
  .showcase {
    padding: 28px 56px;
  }

  .showcase-background {
    height: 260px;
  }

  .showcase-content {
    display: grid;
    grid-template-columns: repeat(17, 1fr);
    grid-template-rows: repeat(6, 70px);
  }

  .showcase-title {
    grid-column: 1 / 6;
    grid-row: 1 / 2;
  }

  .showcase-choose {
    grid-column: 1 / 6;
    grid-row: 3 / 5;
    margin: 0 0 -40px 0;
    justify-self: flex-start;
  }

  .showcase-info {
    grid-column: 12 / 18;
    grid-row: 1 / 2;
  }

  .showcase-post {
    grid-column: 6 / 9;
    grid-row: 1 / 7;
  }

  .showcase-impressions {
    grid-column: 9 / 14;
    grid-row: 2 / 4;
  }

  .showcase-tip {
    grid-column: 14/ 18;
    grid-row: 2 / 4;
  }

  .desktop-arrow-1 {
    display: block;
    grid-column: 4 / 6;
    grid-row: 5 / 6;
    margin-bottom: -12px;
  }

  .desktop-arrow-2 {
    display: block;
    grid-column: 9 / 11;
    grid-row: 4 / 5;
    align-self: flex-end;
    margin-bottom: -12px;
  }

  .desktop-arrow-3 {
    display: block;
    grid-column: 12 / 15;
    grid-row: 4 / 5;
  }
  .desktop-arrow-1-animating {
    animation: horizontal 1.5s ease-in-out infinite;
    z-index: -1;
  }
  .desktop-arrow-2-animating {
    animation: vertical 1.5s ease-in-out infinite;
  }
  .desktop-arrow-3-animating {
    animation: horizontal 1.5s ease-in-out infinite;
  }

  @keyframes horizontal {
    0% {
      transform: translateX(0);
    }
    50% {
      transform: translateX(12px);
    }
    100% {
      transform: translateX(0);
    }
  }
  @keyframes vertical {
    0% {
      transform: translateY(0);
    }
    50% {
      transform: translateY(12px);
    }
    100% {
      transform: translateY(0);
    }
  }
}
@media screen and (min-width: 1495px) {
  .showcase-choose {
    margin: 0 0 -10px 0;
  }
}
</style>
